<a href="https://colab.research.google.com/github/felipelimapy/Study-on-Machine-Learning/blob/main/Teste_Treino.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("/content/admission.csv", delimiter=';')

In [3]:
x=df.iloc[:,:-1].values #atribuindo as amostras independentes a variavel X

In [4]:
y= df.iloc[:,-1].values #pegando as amostras da ultima coluna

In [5]:
from sklearn.impute import SimpleImputer

In [6]:
imputer= SimpleImputer(missing_values=np.nan, strategy='median') 

In [7]:
x[:,1:]= imputer.fit_transform(x[:,1:])

In [8]:
from sklearn.preprocessing import LabelEncoder #bibiloteca para rotulos aleatórios na coluna

In [9]:
labelencoder_x=LabelEncoder()

In [10]:
x[:,0]= labelencoder_x.fit_transform(x[:,0]) #atribuindo valores randomicos na coluna 0 do daset

In [11]:
# rotulos binários não influenciam na decisão do modelo

In [12]:
x=x[:,1:]

In [13]:
d=pd.get_dummies(x[:,0]) #atribuindo valores binários na coluna 0 do dataset

In [14]:
x= np.insert(x,0, d.values, axis=1) #colocando os valores na coluna de X a partir da coluna 0 os valores de D

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
xTrain,xTest,yTrain,yTest= train_test_split(x,y, test_size=0.3)

In [17]:
print(xTrain)

[[0 0 0 1 0 0 0 0 0 330.0 115.0 5.0 4.5 3.0 9.34 1.0]
 [0 0 0 0 0 0 0 1 0 324.0 107.0 4.0 4.0 4.5 8.87 1.0]
 [1 0 0 0 0 0 0 0 0 302.0 102.0 1.0 2.0 1.5 8.0 0.0]
 [0 0 0 0 0 1 0 0 0 308.0 101.0 2.0 3.0 4.0 7.9 0.0]
 [0 1 0 0 0 0 0 0 0 321.0 109.0 3.0 3.0 4.0 8.2 1.0]
 [0 0 1 0 0 0 0 0 0 322.0 110.0 3.0 3.5 2.5 8.67 1.0]]


NORMALIZANDO OS DADOS


In [18]:
from sklearn.preprocessing import StandardScaler #importando o normalizador para deixar os dados mais ou menos parecidos

In [19]:
scaleX= StandardScaler()

In [20]:
xTrain=scaleX.fit_transform(xTrain)   #fit_transform= computa os parâmentros da variavel e transforma essa aplicação nos dados

In [21]:
xTest=scaleX.fit_transform(xTest)

In [22]:
print (xTrain)

[[-0.4472136  -0.4472136  -0.4472136   2.23606798  0.         -0.4472136
   0.         -0.4472136   0.          1.25843366  1.60248593  1.54919334
   1.4596009  -0.24253563  1.64793747  0.70710678]
 [-0.4472136  -0.4472136  -0.4472136  -0.4472136   0.         -0.4472136
   0.          2.23606798  0.          0.63783624 -0.0696733   0.77459667
   0.83405766  1.21267813  0.72952173  0.70710678]
 [ 2.23606798 -0.4472136  -0.4472136  -0.4472136   0.         -0.4472136
   0.         -0.4472136   0.         -1.63768764 -1.11477282 -1.54919334
  -1.66811531 -1.69774938 -0.97052444 -1.41421356]
 [-0.4472136  -0.4472136  -0.4472136  -0.4472136   0.          2.23606798
   0.         -0.4472136   0.         -1.01709022 -1.32379273 -0.77459667
  -0.41702883  0.72760688 -1.16593205 -1.41421356]
 [-0.4472136   2.23606798 -0.4472136  -0.4472136   0.         -0.4472136
   0.         -0.4472136   0.          0.32753753  0.34836651  0.
  -0.41702883  0.72760688 -0.57970923  0.70710678]
 [-0.4472136  -0.

In [23]:
print (xTest)

[[ 0.          0.          0.          0.         -0.70710678  0.
  -0.70710678  0.          1.41421356  1.40985094  1.41169791  1.22474487
   1.29777137  1.33630621  1.40451644  0.70710678]
 [ 0.          0.          0.          0.          1.41421356  0.
  -0.70710678  0.         -0.70710678 -0.60879927 -0.6328301   0.
  -0.16222142 -0.26726124 -0.84543708  0.70710678]
 [ 0.          0.          0.          0.         -0.70710678  0.
   1.41421356  0.         -0.70710678 -0.80105167 -0.77886781 -1.22474487
  -1.13554995 -1.06904497 -0.55907936 -1.41421356]]
