<a href="https://colab.research.google.com/github/felipelimapy/Study-on-Machine-Learning/blob/main/Teste_Treino.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import numpy as np
import pandas as pd

In [29]:
df=pd.read_csv("/content/admission.csv", delimiter=';')

In [30]:
x=df.iloc[:,:-1].values #atribuindo as amostras independentes a variavel X

In [31]:
y= df.iloc[:,-1].values #pegando as amostras da ultima coluna

In [32]:
from sklearn.impute import SimpleImputer

In [33]:
imputer= SimpleImputer(missing_values=np.nan, strategy='median') 

In [34]:
imputer= imputer.fit_transform(x[:,1:])

In [35]:
from sklearn.preprocessing import LabelEncoder #bibiloteca para rotulos aleatórios na coluna

In [36]:
labelencoder_x=LabelEncoder()

In [37]:
x[:,0]= labelencoder_x.fit_transform(x[:,0]) #atribuindo valores randomicos na coluna 0 do daset

In [38]:
# rotulos binários não influenciam na decisão do modelo

In [39]:
x=x[:,1:]

In [40]:
d=pd.get_dummies(x[:,0]) #atribuindo valores binários na coluna 0 do dataset

In [41]:
x= np.insert(x,0, d.values, axis=1) #colocando os valores na coluna de X a partir da coluna 0 os valores de D

In [43]:
from sklearn.model_selection import train_test_split

In [44]:
xTrain,xTest,yTrain,yTest= train_test_split(x,y, test_size=0.3)

In [45]:
print(xTrain)

[[0 1 0 0 0 0 0 0 0 321 109 3 3.0 4.0 8.2 1]
 [0 0 0 0 0 0 1 0 0 314 103 2 2.0 3.0 8.21 0]
 [0 0 0 1 0 0 0 0 0 330 115 5 4.5 3.0 9.34 1]
 [1 0 0 0 0 0 0 0 0 302 102 1 2.0 1.5 8.0 0]
 [0 0 1 0 0 0 0 0 0 322 110 3 3.5 2.5 8.67 1]
 [0 0 0 0 0 0 0 0 1 337 118 4 4.5 4.5 9.65 1]]
