<a href="https://colab.research.google.com/github/felipelimapy/Study-on-Machine-Learning/blob/main/Teste_Treino.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
import numpy as np
import pandas as pd

In [56]:
df=pd.read_csv("/content/admission.csv", delimiter=';')

In [57]:
x=df.iloc[:,:-1].values #atribuindo as amostras independentes a variavel X

In [58]:
y= df.iloc[:,-1].values #pegando as amostras da ultima coluna

In [59]:
from sklearn.impute import SimpleImputer

In [60]:
imputer= SimpleImputer(missing_values=np.nan, strategy='median') 

In [61]:
imputer= imputer.fit_transform(x[:,1:])

In [62]:
from sklearn.preprocessing import LabelEncoder #bibiloteca para rotulos aleatórios na coluna

In [63]:
labelencoder_x=LabelEncoder()

In [64]:
x[:,0]= labelencoder_x.fit_transform(x[:,0]) #atribuindo valores randomicos na coluna 0 do daset

In [65]:
# rotulos binários não influenciam na decisão do modelo

In [66]:
x=x[:,1:]

In [67]:
d=pd.get_dummies(x[:,0]) #atribuindo valores binários na coluna 0 do dataset

In [68]:
x= np.insert(x,0, d.values, axis=1) #colocando os valores na coluna de X a partir da coluna 0 os valores de D

In [69]:
from sklearn.model_selection import train_test_split

In [70]:
xTrain,xTest,yTrain,yTest= train_test_split(x,y, test_size=0.3)

In [71]:
print(xTrain)

[[0 0 1 0 0 0 0 0 0 322 110 3 3.5 2.5 8.67 1]
 [0 0 0 0 1 0 0 0 0 316 104 3 3.0 3.5 8.0 1]
 [0 1 0 0 0 0 0 0 0 321 109 3 3.0 4.0 8.2 1]
 [0 0 0 0 0 1 0 0 0 308 101 2 3.0 4.0 7.9 0]
 [1 0 0 0 0 0 0 0 0 302 102 1 2.0 1.5 8.0 0]
 [0 0 0 0 0 0 1 0 0 314 103 2 2.0 3.0 8.21 0]]


NORMALIZANDO OS DADOS


In [72]:
from sklearn.preprocessing import StandardScaler #importando o normalizador para deixar os dados mais ou menos parecidos

In [73]:
scaleX= StandardScaler()

In [75]:
xTrain=scaleX.fit_transform(xTrain)   #fit_transform= computa os parâmentros da variavel e transforma essa aplicação nos dados

In [77]:
xTest=scaleX.fit_transform(xTest)

In [78]:
print (xTrain)

[[-0.4472136  -0.4472136   2.23606798  0.         -0.4472136  -0.4472136
  -0.4472136   0.          0.          1.16108528  1.50372088  0.89442719
   1.34164079 -0.65850461  2.00556329  1.        ]
 [-0.4472136  -0.4472136  -0.4472136   0.          2.23606798 -0.4472136
  -0.4472136   0.          0.          0.30804303 -0.24253563  0.89442719
   0.4472136   0.47036043 -0.64653027  1.        ]
 [-0.4472136   2.23606798 -0.4472136   0.         -0.4472136  -0.4472136
  -0.4472136   0.          0.          1.01891157  1.21267813  0.89442719
   0.4472136   1.03479296  0.14513945  1.        ]
 [-0.4472136  -0.4472136  -0.4472136   0.         -0.4472136   2.23606798
  -0.4472136   0.          0.         -0.82934663 -1.11566388 -0.4472136
   0.4472136   1.03479296 -1.04236513 -1.        ]
 [ 2.23606798 -0.4472136  -0.4472136   0.         -0.4472136  -0.4472136
  -0.4472136   0.          0.         -1.68238888 -0.82462113 -1.78885438
  -1.34164079 -1.78736965 -0.64653027 -1.        ]
 [-0.44721

In [79]:
print (xTest)

[[ 0.          0.          0.         -0.70710678  0.          0.
   0.          1.41421356 -0.70710678 -1.19216603 -1.3641205  -0.70710678
  -1.41421356  0.70710678 -1.29940719  0.        ]
 [ 0.          0.          0.          1.41421356  0.          0.
   0.         -0.70710678 -0.70710678 -0.06274558  0.35897908  1.41421356
   0.70710678 -1.41421356  0.16632412  0.        ]
 [ 0.          0.          0.         -0.70710678  0.          0.
   0.         -0.70710678  1.41421356  1.25491161  1.00514142 -0.70710678
   0.70710678  0.70710678  1.13308307  0.        ]]
